version: '3'
services:
  langgraph:
    build: .
    ports:
      - "2024:2024"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
    volumes:
      - ./langgraph_project:/app/langgraph_project
      - ./src:/app/src
    command: python server.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2024/docs"]
      interval: 30s
      timeout: 10s
      retries: 3 